name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy ke Hosting via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/public_html/pengasuhan.smaplusasthahannas.id
            git pull origin main
            ~/bin/composer install --no-dev --optimize-autoloader --no-interaction
            /usr/local/bin/php artisan migrate --force
            /usr/local/bin/php artisan config:cache
            /usr/local/bin/php artisan route:cache
            /usr/local/bin/php artisan view:cache
            /usr/local/bin/php artisan queue:restart